spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/monitortest?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  freemarker:
    request-context-attribute: request
    template-loader-path: classpath:/templates/
    suffix: .html
server:
  port: 6060

mybatis:
  type-aliases-package: gee.example.mybatissample.**.dao
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
